version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  test:
    build: .
    command: mix test
    environment:
      MIX_ENV: test
    volumes:
      - .:/app/
    links:
      - "db:database"
